.MODEL SMALL


.DATA
   N1 DB "ENTER THE FIRST NUMBER: $"
   N2 DB 10D,"ENTER THE SECOND NUMBER: $" 
   
   AND_OP DB 10D,"RESULT OF AND OPERATION: $"  
   OR_OP DB 10D,"RESULT OF OR OPERATION: $"     
  

.CODE
   MOV AX,@DATA
   MOV DS,AX  
   
   MOV AH,09H
   MOV DX,OFFSET N1
   INT 21H           ;READ N1 CHARACTER
   
   MOV AH,01H
   INT 21H
   MOV BL,AL         ;STORE N1 CHARACTER IN BL
   SUB BL,30H        ;CONVERT N1 CHARACTER TO INTEGER IN BL     
   
   MOV AH,09H
   MOV DX,OFFSET N2
   INT 21H           ;READ N2 CHARACTER
   
   MOV AH,01H
   INT 21H           
   SUB AL,30H        ;CONVERT N2 CHARACTER TO INTEGER IN AL     
   
   MOV CL,AL
   
   AND AL,BL
   OR BL,CL
   
   ADD AL,30H
   ADD BL,30H
   ADD CL,30H
   ADD DL,30H
   
   MOV AH,09H
   MOV DX,OFFSET AND_OP
   INT 21H
   MOV AH,02H
   MOV DL,AL
   INT 21H
   
   MOV AH,09H
   MOV DX,OFFSET OR_OP
   INT 21H
   MOV AH,02H
   MOV DL,BL
   INT 21H
   
   

END




